var lib=[
["单选题","国际报务知识","在中国南方航空的英文发音中，关于“南方”的发音，以下哪一项是正确的（ ）","[ˈsʌðən]"," [saʊθən]","[sɑ:ðən]"],
["单选题","国际报务知识","槟城无线电失效程序；槟城起飞后，无线电通讯失效，起始高度保持（  ）分钟后，可以上升到既定的巡航高度？","2mins","1mins","3mins"],
["单选题","国际报务知识","首尔运行过程中，在获得推出指令多长时间后，如若没有推出，指令视为作废，需要重新申请？（  ）","1min","2min","3min"],
["单选题","国际报务知识","在“HIRO”运行期间，RET（rapid exit taxiway）的既定速度是多少？（  ）","50kt","45kt","35kt"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-49-35.png />在紧急下降中，下降到MORA，指的是上图中的哪个数值（  ）","5800a","7000T","FL130"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-50-04.png />在紧急下降程序中，下降到MEA，指的是上图中的哪个数值（  ）","FL130","7000T","5800a"],
["单选题","国际报务知识","以下关于APU的全称，正确的是？（  ）","Auxiliary Power Unit","Accumulate Power Unit","Assist Power Unit"],
["单选题","国际报务知识","以下能替代地面电源（Ground power）的词汇是？（  ）","External Power","Auxiliary Power","Build—In Power"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-40-02.png />上图中的序号10，“c” 表示的是什么？（  ）","Civil","Cargo only","Continuous"],
["单选题","国际报务知识","在首尔运行中，管制员执行CDO程序，请问，CDO的全称是？（  ）","CONTINUOUS DESCENT OPERATION","CONSTANT DESCENT OPERATION","CONTINUOUS DECELERATE OPERATION"],
["单选题","国际报务知识","事件背景；2018年9月17日，洛杉矶-浦东，由于旅客哮喘发作，需要返航，联系管制部门寻求地面应急医疗救助时，管制需要机组表述病情，从以下词汇中筛选出合适的病情描述（  ）","ASTHMA","COUGH","DIARRHEA"],
["单选题","国际报务知识","边检的英语是（  ）","Immigration","Customs","Quarantine"],
["单选题","国际报务知识","在应急医疗词汇中，表示旅客晕厥的词汇是？（  ）","Faint","Diarrhea","Palsy"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-51-10.png />请问，在进近图上，该符号表示的是什么？（  ）","VOR","DME","NDB"],
["单选题","国际报务知识","应急运行情况下，表示迷航（LOST）的词是？（  ）","Disorientation","Drift","Incursion"],
["单选题","国际报务知识","在应急医疗通讯中，关于发烧的词汇是（  ）？","Fever","Fainted","Incursion"],
["单选题","国际报务知识","以下词汇中，能代替轮胎爆破（Burst Tyre）的是（  ）","Flat Tyre","Flame Tyre","Puncture"],
["单选题","国际报务知识","在应急医疗通讯中，关于中风旅客的词汇是？（  ）","Stroke","Flu","Cough"],
["单选题","国际报务知识","终止进近的英语表达；（  ）","MISS APPROACH","GO AROUND","ABORT APPROACH"],
["单选题","国际报务知识","“HIRO”首尔运行，ATIS里出现的“HIRO”代表什么意思？（  ）","High Intensity Runway Operation","Helicopter Isolation Runway Operation","High Intensity Radio Operation"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-40-02.png />上图中的序号11，“Ｈ24”表示的是什么？（  ）","Continuous day and night service","High intensity 24","Height above threshold"],
["单选题","国际报务知识","在机场细则中，以下哪个属于对准跑道指示灯？（  ）","RAIL","HIRL","ALS"],
["单选题","国际报务知识","METAR 的航空气象报告的发布周期是（  ）","HALF-HOURLY OR HOURLY","HALF-HOURLY ","HOURLY"],
["单选题","国际报务知识","检疫的英语是（  ）","Quarantine","Immigration","Customs"],
["单选题","国际报务知识","以下描述遭遇颠簸程度的词汇中，哪一项是描述剧烈颠簸的？（  ）","Severe","Moderate","Slight"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-43-53.png />请问图中的3600T表示的是什么意思！？（  ）","MOCA最低超障高度","MORA最低偏航高度","MAA批准最低高度"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-44-42.png />图中绿色的“39”表示的是什么意思！？（  ）","网格最低偏航高度（14000英尺以下为绿色）","MORA最低偏航高度","区域图覆盖范围"],
["单选题","国际报务知识","METAR WMMM 301220Z 14005KT 1200 0600E R12/1000N DZ BCFG VV// 08/07 Q1004 NOSIG中的R12/1000N 中的“N”表示什么意思？（  ）","NO APPARENT TENDENCY","NAUTICAL MILE","NOT ABOVE"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-52-05.png />请问，在进近图上，该符号表示的是什么？（  ）","VORDME","NDB","VOR"],
["单选题","国际报务知识","在航空数字用于发音中，关于“9”的发音，哪一项是正确的？（  ）","NINER","NIGHT","NINE"],
["单选题","国际报务知识","以下词汇中，表示升限的词是？（  ）","Ceiling","Optimum Altitude","Ideal Altitude"],
["单选题","国际报务知识","航空词汇中，超越前机的词汇是？（  ）","Overtake ","Overshot","Overcome"],
["单选题","国际报务知识","事件背景，2018年8月16日，厦门航空在菲律宾马尼拉机场冲出跑道，管制员在询问机组过程中，机组没有作出回答，假如你是当班机组，如何描述情况（  ）","OVERSHOOT THE RUNWAY","PASS THROUGH THE RUNWAY","TRAP INTO THE RUNWAY"],
["单选题","国际报务知识","在吉隆坡运行过程过，地面席位会要求机组报告POB，请问，POB是什么的简称？（  ）","PERSONS ON BOARD","PASSANGERS ON BOARD","PILOTS ON BOARD"],
["单选题","国际报务知识","航空词汇中，以下关于“右”哪一项是正确的？（  ）","Starboard","Port","Reverse"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-40-02.png />上图中的序号6，“P”表示的是什么？（  ）","Paved","Prohibited area","Propeller aircraft only"],
["单选题","国际报务知识","海关的英语是（  ）","Customs","Quarantine","Immigration"],
["单选题","国际报务知识","在机场细则中，以下哪个属于进近灯？（  ）","ALS","RAIL","HIRL"],
["单选题","国际报务知识","在机场细则中，以下哪个属于高强度跑道灯（  ）","HIRL","RAIL","TDZ"],
["单选题","国际报务知识","以下选项中，能代替右转一圈（Right Hand Circle）的词汇是（  ）？","Right Orbit","Right Semicycle","Right Pattern"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-55-37.png />机场进近图中，索引号“21—3”中的1，表示的是什么类型的进近（  ）","ILS，MLS，GLS","RNAV，VISUAL ","RNAV（GPS）"],
["单选题","国际报务知识","以下，能代替中断起飞（rejected take off）的词是？（  ）","Aborted Take off","Roll Out","Reverse "],
["单选题","国际报务知识","以下，能代替跑道180掉头（U turn）的词是？（  ）","Backtrack","Roll Out","Shift To"],
["单选题","国际报务知识","跑道入侵的英语表达；（  ）","RUNWAY INCURSION","RUNWAY INTERFERENCE","RUNWAY COLLISION"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-54-55.png />机场进近图中，索引号“23—1”中的3，表示的是什么类型的进近（  ）","VOR","RVAV（GPS）","ILS，MLS，GLS"],
["单选题","国际报务知识","航空词汇中，以下关于“左”哪一项是正确的？（  ）","Port","Starboard","Dextroversion"],
["单选题","国际报务知识","事件背景，2017年2月24日，武汉-广州，由于旅客心脏病发作，需要返航，联系管制部门寻求地面应急医疗救助时，管制需要机组表述病情，从以下词汇中筛选出合适的病情描述（  ）","HEART ATTACK","STOMACHACHE","ALLERGY"],
["单选题","国际报务知识","以下能代替复飞“go around”的词汇是？（  ）","Overshot","Teminated","Pass by"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-51-39.png />请问，在进近图上，该符号表示的是什么（  ）","DME","VOR","NDB"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-52-37.png />请问，在进近图上，该符号表示的是什么？（  ）","NDB","VOR","DME"],
["单选题","国际报务知识","SELCAL （SELECTIVE CALLING SYSTEM）U/S ON THE GROUND DUE TO WIP 中的“WIP”是什么意思？（  ）","WORK IN PROGRESS","WORK IN PROCESS","WORK IN PROGRAM"],
["单选题","国际报务知识","在首尔运行期间，Ａ320系列飞机在地面桥载接通的条件下，最迟启动APU时间是？（  ）","撤轮挡时间前30mins","撤轮挡时间前60mins","撤轮挡时间前45mins"],
["单选题","国际报务知识","在VDGS（VISUAL DOCKING GUIDANCE SYSTEM）和机务指挥存在争议的情况下，机组应该怎么做？（  ）","存在争议时，一律跟随机务的指令；","如果VDGS显示的机型正确，跟随VDGS的指令；","停住飞机，跟机坪证实。"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-50-04.png />上图中的65，表示的是什么？（  ）","航段里程","导航设施间的总里程","航路VOR磁径向线"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-43-20.png />请问，Sospa边儿上的实心三角形表示的是什么意思？（  ）","强制报告点","低空强制报告点","非强制报告点"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-41-49.png />在Jeppesen航图中，以上的图标，请问哪个表示的是民用机场（  ）","第一个","第二个","第三个"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-53-52.png />请问，上图中的“NOT TO SCALE”表示的是什么意思？（  ）","不是按比率绘制","非紧急偏航","指向型扇区"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-54-21.png />请问，上图（RKSI 15L VOR进近图）的虚线箭头表示的是什么意思（  ）","目视进近飞行航迹","复飞起始机动航迹","高高度进近飞行航迹"],
["单选题","国际报务知识","飞机在国际（特殊管理的国内）航线上飞行失去通信联络时，对于没有发布特定程序的国家，机长应执行（B）的通讯失效程序","所在国家或地区规定的","国际民航组织的标准","遵循国内航班的"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-45-09.png />请问图框中的“223”表示的是什么？（  ）","导航设施间的总里程","航路总里程","雷达强制监控总里程"],
["单选题","国际报务知识","在地空无线电通讯失效时，管制员使用灯光或信号弹，对起降或在机场机动区内的航空器进行管制，请问，绿色闪亮在地面时，表示什么？（  ）","同意滑行","回到机场的启示位置","脱离现用跑道"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-46-23.png />上图是首尔细则内的两个限制区，请问，RK（P）—73A中的“UNL/GND”表示的是什么？","限制区的垂直范围，从地面到上不封顶","活动限制时间","管理机构"],
["单选题","国际报务知识","“Speed & descent at pilot’s discretion.”在首尔运行中代表什么意思！？（  ）","机组自行掌握速度和下降时机","机组报告速度和下降目标高度","机组基于能量比对，自行申请高度和速度改变。"],
["单选题","国际报务知识","在首尔建立五边盲降之后，管制员指挥“RESUME NORMAL SPEED”的意思是？（  ）","保持速度160kt到五边5NM；","机组恢复正常的减速进近，自行掌握与前机不大于5NM的水平间隔；","减速到最小光洁速度"],
["单选题","国际报务知识","首尔运行的习惯性用语中，“High Speed Descent”指的是？（  ）","尽可能大的下降率","尽可能大的速度","尽可能小的下降率"],
["单选题","国际报务知识","跟进重型飞机从同一跑道入口起飞的离场尾流间隔是 （  ）","无雷达时2分钟","雷达管制时2分钟","3海里的雷达间隔","4—5海里的TCAS间隔"],
["单选题","国际报务知识","首尔执行低能见度运行，由于前机O-CDM时间限制，是否可以申请从前一个道口进跑道，进行减跑道起飞？（  ）","不可以；","起飞限重表有相关数据，即可；","获得管制员同意，即可。"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-45-48.png />请问PEBRI点的非实心星形，表示的是什么？（  ）","RVAV航路点","强制报告点","扇区交接点"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-53-18.png />请问，上图中的三角形表示的是什么？（  ）","强制报告点","扇区交接点","强制飞跃点"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-47-05.png />请问图中的黑色虚线表示的是什么意思？（  ）","国际边界，国界","时区边界","FIR边界"],
["单选题","国际报务知识","<img src=img/Snipaste_2018-12-12_11-47-45.png />上图管制空域中的（P）表示的是什么？（  ）","禁区","危险区","警戒区"],
["单选题","国际报务知识","国际航班运行时，起始B页 3L输入的10%的定义是？（  ）","以巡航末点为基准，在原飞行高度继续飞行10%主航段总飞行时间的用油；","以航程用油为基准，在申请巡航高度继续飞行10%主航段总飞行时间的用油；","改航备降用油，包括在目的地机场复飞，爬升，巡航，下降至最远备降场直接进近及着陆的耗油量。"],
["单选题","国际报务知识","国际或特殊管理的国内航线出入境文件，包括哪些？（  ）","总申报单、 海关关封、卫生检疫证明","总申报单、旅客名单、国际货物清单","总申报单、出入境机组人员名单、海关关封"],
["单选题","国际报务知识","大阪RJBB机场在指挥下降至过渡高度层以下的高度时，习惯以下列哪种形式表述","QNH/inch"," QNH/hpa","Alt Set/inch"],
["单选题","国际报务知识","大阪RJBB机场，ETA时间为1300UTC，请问从BERTH方向进场，是否需要执行CDO程序？","否"," 是"],
["单选题","国际报务知识","放行同意 HELEN 1 DEPARTURE,HABAR transitions，具体航路应为<img src='img/Snipaste_2019-01-02_15-45-31.png' /> ","HELEN—MAIKO—WENDY—SHION—HABAR"," HELEN—MAIKO—KWAT—KTE—HABAR","HELEN—MAIKO—RADAR VEC to HABAR"],
["单选题","国际报务知识","SSP 程序是指？","Special safeguards procedures"," Special secondary procedures","Special slot time procedures"],
["单选题","国际报务知识","Separation for departure 默认为(3mins for LIGHT or MEDIUM aircraft behind HEAVY aircraft),当天指挥从A2/A13进行减跑道起飞（假设性能允许），是否还继续遵循此程序？","NO","YES"],
["单选题","国际报务知识","请看下图<b>google</b>，机场灯光系统里包含着A R T，其含义分别为<img src='img/Snipaste_2019-01-02_15-49-59.png' /> ","A= Approach R=Runway T=Threshold","A=Aerodrome R=Runway T=Threshold","A=Approach R=Runway T=Taxiway"],
["单选题","国际报务知识","飞机注册号  __________","registration number"],
    ["填空题","国际报务知识","地面电源  __________","GPU(ground power unit)"],
    ["填空题","国际报务知识","外部气源  __________","external pneumatic power"], 
    ["填空题","国际报务知识","拖车  __________ ","tug /tow car"],
    ["填空题","国际报务知识","拖把  __________ ","towbar."],
    ["填空题","国际报务知识","辅助动力装置  __________ ","APU(auxiliary power unit)"],
    ["填空题","国际报务知识","前轮转弯  __________ ","N/W STRG （nosewheel steering)"],
    ["填空题","国际报务知识","长推出/短推出  __________ ","long pushback/short pushback."],
    ["填空题","国际报务知识","边缘天气条件  __________ ","marginal weather condition."],
    ["填空题","国际报务知识","中断起飞  __________ ","RTO(reject take off)/abort takeoff."],
    ["填空题","国际报务知识","前轮摆震  __________ ","nose gear vibration"],
    ["填空题","国际报务知识","爆胎  __________ ","tire burst "],
    ["填空题","国际报务知识","失去刹车  __________ ","loss of braking "],
    ["填空题","国际报务知识","不对称刹车  __________ ","asymmetric braking"],
    ["填空题","国际报务知识","前轮转弯故障  __________ ","nosewheel steering fault"],
    ["填空题","国际报务知识","重力放轮  __________ ","L/G gravity extention "],
    ["填空题","国际报务知识","襟/缝 翼卡阻  __________ "," flap/slat jam"],
    ["填空题","国际报务知识","襟/缝翼无法收回  __________ ","flap/slat unretractable"],
    ["填空题","国际报务知识","EGT 超限  __________ ","EGT over limit"],
    ["填空题","国际报务知识","发动机失速  __________ ","engine stall"],
    ["填空题","国际报务知识","发动机尾管喷火  __________ ","engine tailpipe fire "],
    ["填空题","国际报务知识","发动机空中重启  __________ ","engine relight （地面为restart）"],
    ["填空题","国际报务知识","发动机高震动  __________ ","high engine vibration "],
    ["填空题","国际报务知识","发动机故障/失效  __________ ","engine fault/failure"],
    ["填空题","国际报务知识","燃油泄漏  __________ ","fuel leak "],
    ["填空题","国际报务知识","空速不可靠  __________ ","unreliable speed indication "],
    ["填空题","国际报务知识","位置不一致  __________ "," POS disagree"],
    ["填空题","国际报务知识","机载设备降级  __________ ","equipment degration"],
    ["填空题","国际报务知识","客舱失压  __________ ","cabin depressurization"],
    ["填空题","国际报务知识","Noise Abatement Operating Procedures in force for Landing to Runway 06R/06L.<br />1.Extend landing gear after leaving___<br />2.Extend final landing flaps after leaving___","2500/1500"],
    ["填空题","国际报务知识","Japan airspace 对速度有严格要求，进近控制区域，在或低于10000英寸MSL_____kts<br />控制区域，在或低于3000MSL,___kts。高于3000MSL，____kts。","250；200；250"],
    ["填空题","国际报务知识","中日走廊口，对高度有严格限制，AKARA—FUKUE CORRIDOR:向东飞行，需保持FL_____(哪四个高度层?)。在飞跃LAMEN之前，应向ATC申请上述许可高度，如果无法在LAMEN前达到FL250，机组可以申请飞跃LAMEN在或高于FL230，在SADLI前达到FL250。","FL250，FL290，FL310，FL390"],
    ["填空题","国际报务知识","AKARA—FUKUE CORRIDOR:向西飞行，应保持FL_____(哪四个高度层?)，在飞跃ONIKU之前，应向ATC申请上述飞行高度","FL240，FL280，FL300，FL400"],
    ["填空题","国际报务知识","RJBB 机场，过渡高度跟过渡高度层分别为___________","FL140/FL140"],
    ["填空题","国际报务知识","If a in-flight occurs and the situation permits，the Captain shall inform the appropriate air traffic services unit of the dangerous goods onboard the aircraft。Examples for providing most important information are as follows","MAYDAY MAYDAY MAYDAY or PAN PAN PAN ，（ATC name），CZ（flight number），dangerous goods onboard （fire/smoked/leaked），require to（return/divert to）—-airport；Proper shipping name —-，UN number—-，Drill code—-，Quantity——，carried on forward/afterwad compartment，i ask for emergency assistance"],
    ["填空题","国际报务知识","RJBB(KANSAI) Lost communication procedures for arrival aircraft under radar navigationl guidance.<br />If radio communications with KANSAI Approach/Radar are lost for 1 minuet,squawk Mode A/3 code——,and<br />1.Contact KANSAI tower;<br />2.If unable,proceed in accordance with visual flight rules,<br />3.If unable,<br />1)RWY 06L/06R in use,proceed to____at last assigned altitude or ____feet whichever is higher,and execute instrument approach.<br />2)RWY 24L/24R in use,proceed to____VOR/DME at last assigned altitude or ____-feet whichever is higher,and execute instrument approach via____arrival.","GATES，4000ft；AJE，4000ft，LILAC arrival"],
    ["填空题","国际报务知识","at RKSI when ATC use “RESUME NORMAL SPEED” RTF phraseology,pilot shall note that the previously issued speed restriction by ATC is cancelled but comply with SEOUL TMA speed restriction is ____________","MAX 250kt IAS below 10000ft,160kt IAS to 5 NM/DME"],
    ["填空题","国际报务知识","<img src='img/Snipaste_2019-01-02_20-25-33.png' />JEPPESEN 航图红圈部分代表_____","TCH(threshold crossing height)为49ft，displ代表此跑道入口内移"],
    ["简答题","国际报务知识","无论何原因，必须报告发生的RVSM运行误差事件是哪三项？","1.总垂直误差（TVE）≥300英尺（90米）<br />2.高度测量系统误差（ASE）≥245英尺（75米）<br />3.指定高度偏差（AAD）≥300英尺（90米）"],
    ["简答题","国际报务知识","RVSM区域爬升及下降率控制要求是什么，以防止机载防撞系统产生告警？","1.在改变高度爬升或下降时，爬升或下降率不大于1500英尺/分钟<br />2.在爬升或下降至管制许可飞行高度层的最后300米垂直范围内，爬升或下降率保持在500～1000英尺/分钟<br />3.当航空器爬升或下降率小于500英尺/分钟时，飞行机组应当报告管制员，以便管制员合理推测航空器抵达管制许可飞行高度层的时间"],
    ["简答题","国际报务知识","RVSM报告程序和时间限制是如何的?","1.飞行机组24小时内向机组所在飞行单位、运行控制部门报告<br />2.运行控制部门值班人员应即时向公司总值班经理报告，同时报告公司安全监察部、法律标准部，安监部或飞机执管单位按以下原则向民航属地局报告：（发生的不安全事件由事发单位照《中国南方航空集团（股份）有限公司安全信息管理规定》执行信息报送程序）<br />a)如果发生的报告事件造成危险冲突，安全监察部在事发24小时内将该事件的初步原因分析和防止类似事件再次发生的措施报告给民航属地局航空安全办公室和运行安全监督办公室<br />b)如果发生的报告事件未造成危险冲突，飞行执管单位在事发72小时内将该事件的初步原因分析和防止类似事件再次发生的措施报告给民航属地局航空安全办公室和运行安全监督办公室"]

]